apiVersion: v1
kind: Service
metadata:
  name: kubelet-metrics-test
  namespace: kube-system
spec:
  selector:
    app: kindnet
    k8s-app: kindnet
  clusterIP: None
  ports:
    - name: https-metrics
      port: 10250
      protocol: TCP
      targetPort: 10250
    - name: http-metrics
      port: 10255
      protocol: TCP
      targetPort: 10255
    - name: cadvisor
      port: 4194
      protocol: TCP
      targetPort: 4194
  type: ClusterIP
